{
 "title": "Lighthouse - Dashboard - All sites",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Lighthouse Graphs\n\nThe colored panels are using the [Lighthouse scoring](https://docs.google.com/spreadsheets/d/1Cxzhy5ecqJCucdf1M0iOzM8mIxNc7mmx107o5nj38Eo/edit#gid=283330180) thresholds.\n\n\n\n"
  },
  {
   "title": "Accessibility Score",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "accessibility-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Best practice score",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "best-practices-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "performance-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SEO Score",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "seo-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Progressive Web App Score",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "pwa-score",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "firstContentfulPaint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Meaningful Paint",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "firstMeaningfulPaint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "speedIndex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time to Interactive",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "interactive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}